import UI from "./UI";
export default class CLI extends UI {
    constructor(silent?: boolean, verbose?: boolean);
    /**
     * Displays a list of skipped contracts
     * @param  {TruffleConfig}  config
     * @return {Object[]}       skipped array of objects generated by `assembleTargets` method
     */
    reportSkipped(config: any, skipped?: any[]): void;
    report(text: string, args?: any[]): void;
}
//# sourceMappingURL=CLI.d.ts.map