name: main-build

on:
  push:
    branches:
      - main
    paths-ignore:
      - "docs/"
      - "**.md"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      # Cloning
      - uses: actions/checkout@v3

      # Setup and Caching
      - name: Use latest Node.js LTS version
        uses: actions/setup-node@v3
        with:
          node-version: lts/*

          # NPM Cache using all package-lock files as hash
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'

      # Dependencies
      - name: Solidity - Install Dependencies
        run: npm ci

      # Building
      - name: Solidity - Build
        run: npm run build
