name: verify

on:
  push:
    branches: [main, develop]
    paths-ignore:
      - "docs/"
      - "**.md"
  pull_request:
    branches: [main, develop]
    paths-ignore:
      - "docs/"
      - "**.md"

jobs:
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      # Keep running other versions when a job fails
      fail-fast: false

      matrix:
        # Run the pipeline on all the currently supported OS versions
        os: [ubuntu-latest]

        # Run the pipeline on all the currently supported LTS versions and the upcoming version
        node-version: [19]

        # Run the pipeline on all the currently supported architectures
        architecture: [x64]

    steps:
      # Cloning
      - uses: actions/checkout@v2

      # Setup
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          architecture: ${{ matrix.architecture }}

      # Caching
      - name: Get NPM cache directory
        id: npm-cache-dir
        run: echo "::set-output name=dir::$(npm config get cache)"
      - name: Cache Node.js modules
        uses: actions/cache@v2
        with:
          path: ${{ steps.npm-cache-dir.outputs.dir }}
          key: ${{ runner.os }}-node-${{ hashFiles('package.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
            ${{ runner.os }}-

      # Dependencies
      - name: Solidity - Install Dependencies
        run: npm install

      # Format
      - name: Solidity - Run Formatter
        run: npm run format:check

      # Linting
      - name: Solidity - Run Linter
        run: npm run lint
